export const NOTES_NEW_NOTE = '[NOTES] NEW_NOTE';
export const NOTES_DROP_NOTE = '[NOTES] DROP_NOTE';
export const NOTES_SET_ACTIVE = '[NOTES] SET_ACTIVE';
export const NOTES_UPDATED_NOTE = '[NOTES] UPDATED_NOTE';
export const NOTES_DISPLAY_IN_SIDEBAR = '[NOTES] DISPLAY_IN_SIDEBAR';
export const NOTES_CLEANING_WHEN_LOGOUT = '[NOTES] CLEANING_WHEN_LOGOUT';

export const NOTES_CHANGE_ORDER = '[NOTES] CHANGE_ORDER';

const TYPES_NOTES = {
    NOTES_NEW_NOTE,
    NOTES_DROP_NOTE,
    NOTES_SET_ACTIVE,
    NOTES_UPDATED_NOTE,
    NOTES_DISPLAY_IN_SIDEBAR,
    NOTES_CLEANING_WHEN_LOGOUT,
    NOTES_CHANGE_ORDER,
};

export default TYPES_NOTES;